version: '3'

services:

  analyzer-kadabra-api:
    container_name: analyzer-kadabra-api
    image: greenstamp/analyzer-kadabra-api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4000:3000
    environment:
      DELIVER_RESULTS_ENDPOINT: 'http://51.210.255.156:3000/api/result'
      KADABRA_HOME: ${KADABRA_HOME}
      UPLOADS_HOME: ${UPLOADS_HOME}
    volumes:
      - '/data/greenstamp/analyzer-kadabra-api:/data'